export const RENDER_LOADING_PAGE = 'RENDER_LOADING_PAGE';
export const POST_USER = 'POST_USER';
export const PUT_CREDENTIALS = 'PUT_CREDENTIALS';
export const PUT_PROFILE_INFO = 'PUT_PROFILE_INFO';
export const PUT_USER_ADDRESS_INFO = 'PUT_USER_ADDRESS_INFO';
